import type { FeaturesConfig, PlatformConfig } from '../config/types.js';

export const allEnabledFeatures: FeaturesConfig = {
  businessDirectory: true,
  eventsCalendar: true,
  communityNoticeboard: true,
  communityGroups: true,
  localHistory: true,
  messaging: true,
  dealsHub: true,
  b2bNetworking: true,
  emergencyAlerts: true,
  socialFeedAggregation: true,
  surveySystem: true,
  reviewsAndRatings: true,
  multilingual: true,
  pwaInstallation: true,
  smsAlerts: true,
  whatsappAlerts: true,
};

export function createValidPlatformConfig(): PlatformConfig {
  return {
    platform: { id: 'test', version: '1.0.0' },
    location: {
      suburbName: 'Test',
      suburbNameShort: 'Test',
      region: 'Test Region',
      city: 'Sydney',
      state: 'NSW',
      stateFullName: 'New South Wales',
      country: 'Australia',
      countryCode: 'AU',
      postcode: '2000',
      postcodeRange: ['2000'],
      coordinates: { latitude: -33.8, longitude: 151.2 },
      boundingBox: { north: -33.7, south: -33.9, east: 151.3, west: 151.1 },
      timezone: 'Australia/Sydney',
      locale: 'en-AU',
      currency: 'AUD',
      currencySymbol: '$',
      phoneCountryCode: '+61',
      defaultSearchRadiusKm: 5,
      maxSearchRadiusKm: 20,
    },
    branding: {
      platformName: 'Test Hub',
      platformNameShort: 'Test',
      tagline: 'Test tagline',
      description: 'Test description',
      legalEntityName: 'Test Entity',
      copyrightHolder: 'Test Holder',
      colors: {
        primary: '#2C5F7C',
        secondary: '#E67E22',
        accent: '#F39C12',
        success: '#27AE60',
        error: '#E74C3C',
        warning: '#F39C12',
        info: '#3498DB',
      },
      logos: {
        primary: '/logo.svg',
        light: '/logo-light.svg',
        dark: '/logo-dark.svg',
        favicon: '/favicon.ico',
        appleTouchIcon: '/apple-touch-icon.png',
      },
      socialHashtags: { primary: '#Test', secondary: ['#TestSydney'] },
    },
    partners: {
      council: {
        name: 'Test Council',
        website: 'https://council.example.com',
        logo: '/council.png',
        contactEmail: 'council@example.com',
      },
      chamber: {
        name: 'Test Chamber',
        website: 'https://chamber.example.com',
        logo: '/chamber.png',
        contactEmail: 'chamber@example.com',
      },
    },
    features: { ...allEnabledFeatures },
    multilingual: {
      defaultLanguage: 'en',
      supportedLanguages: [
        { code: 'en', name: 'English', nativeName: 'English', rtl: false, enabled: true },
      ],
      autoTranslationEnabled: true,
    },
    seo: {
      titleTemplate: '{page} | {platformName}',
      defaultTitle: 'Test Hub',
      defaultDescription: 'Test description',
      defaultKeywords: ['test'],
      ogImage: '/og.jpg',
      twitterHandle: '@test',
    },
    contact: {
      supportEmail: 'support@example.com',
      generalEmail: 'hello@example.com',
      feedbackEmail: 'feedback@example.com',
      privacyEmail: 'privacy@example.com',
    },
    legal: {
      termsUrl: '/legal/terms',
      privacyUrl: '/legal/privacy',
      cookieUrl: '/legal/cookies',
      accessibilityUrl: '/legal/accessibility',
      abn: '00 000 000 000',
    },
    limits: {
      maxBusinessPhotos: 50,
      maxPhotoSizeMb: 5,
      maxMenuFileSizeMb: 10,
      maxActivePromotions: 5,
      maxNoticeboardPostsPerUser: 3,
      noticeboardExpiryDays: 30,
      maxNewConversationsPerDay: 10,
      maxFlashDealsPerWeek: 2,
      reviewEditWindowDays: 7,
      accountDeletionGracePeriodDays: 14,
    },
    analytics: { googleAnalyticsId: '', enableCookieConsent: true },
  };
}
